### ISSUE TITLE
[Bug] UCCL-EP Megatron training crashes + 5× slower than NCCL-native on 4× p5en EFAv3 (DS-V3 FP8 EP=32)

### ISSUE THREAD

**Issue by AutoJunjie** [uccl-project/uccl#893]
**Environmen**t:

- AWS EKS, 4× p5en.48xlarge (8× H200, 16× 400 Gb/s EFAv3 per node), 32 GPUs, us-east-2a
- `uccl==0.1.0.post6`, `ep.abi3.so` rebuilt locally with `-DUSE_DMABUF`
- Megatron-core 0.17.0 direct (torchrun, no Ray), DeepSeek-V3-like MoE
- HIDDEN=7168, 12 layers, 256 experts, topk=8, seq=4096
- EP=32 (flex dispatcher, `--moe-enable-deepep`), PP=1, TP=1, micro-bs=1, global-bs=32
- Dtype: FP8 hybrid (`--fp8-format hybrid`), low-latency mode

**Setup notes**:

Stock `uccl==0.1.0.post6` pip wheel is unusable on EFAv3 — `ibv_reg_mr_iova2` returns `ENOTSUP` because the DMABUF path is gated behind `INTEL_RDMA_NIC`. We rebuilt `ep.abi3.so` with `-DUSE_DMABUF` to get past this. To reach step 1 we also needed:

1. `ep/buffer.py:1495` — non-cached internode dispatch hardcodes `previous_event=None`, which trips `EP_HOST_ASSERT(previous_event.has_value() and async)`. Patched to `getattr(previous_event, "event", None)`.
2. A `sitecustomize.py` shim monkey-patching `deep_ep.Buffer.dispatch/.combine` to coerce `async_finish=False, allocate_on_comm_stream=False` when `previous_event is None` — Megatron 0.17's `MoEFlexTokenDispatcher` defaults to async + comm-stream, which trips the same assert without the shim.

Happy to share either patch if useful.

**Symptom**:

Training crashes intermittently (step 94–112, unpredictable), before step 120 in every run we attempted. `test_internode.py` at paper config (`--num-experts=288 --hidden=7168 --topk=8 --num-tokens=4096`, 32 ranks) always passes — dispatch NVL 57.0 GB/s (FP8) / 59.1 GB/s (BF16), combine NVL 44.1 GB/s, which meets or exceeds the paper's 54 / 43 GB/s numbers on this cluster. So the transport layer itself looks healthy; failures only appear during actual Megatron training.

Three runs, three crash signatures, all before step 120:

Run A (crashed step 112) and Run B (crashed step 95) — worker log:

```
Assertion failed: DeepEP dispatch CPU timeout
  at uccl_ep.cc:948 (NUM_TIMEOUT_CYCLES, compiled-in, no runtime knob)
```

Run C (crashed step 94), after applying the README-mandated NCCL env alignment (`NCCL_IB_GID_INDEX=0`, `NCCL_SOCKET_IFNAME=enp71s0` to match the `UCCL_*` equivalents) — worker log:

```
[Rank X] ProcessGroupNCCL Watchdog thread terminated with exception:
CUDA error: unspecified launch failure
on TENSOR_AND_DATA_PARALLEL_GROUP_WITH_CP
```

The NCCL env fix shifted the crash mode but did not recover throughput — median step time stayed at ~6.3 s vs ~1.17 s for the NCCL-native baseline on identical hparams (≈ 5.4× slower, or −81 % MFU: 7.72 % → 1.43 % of peak FP8 on H200). The run-C signature is consistent with something disturbing GPU stream state while NCCL is mid-collective on a non-EP process group — e.g., the UCCL proxy thread touching a stream NCCL is also using.

Loss-curve parity is preserved: over steps 1–10, UCCL-EP vs NCCL baseline max |Δ| = 1.81 %. When it runs, the math is correct — this is purely a throughput + stability regression.

**Questions**:

1. Is this failure family (`uccl_ep.cc:948` CPU timeout inside DeepEP dispatch during Megatron training, despite the transport microbench being healthy on the same cluster) a known issue on EFAv3 / p5en? Is there a runtime knob for `NUM_TIMEOUT_CYCLES`, or is re-compiling the only path today?
2. The run-C signature — `ProcessGroupNCCL watchdog: CUDA unspecified launch failure` on a non-EP group (`TENSOR_AND_DATA_PARALLEL_GROUP_WITH_CP`) while UCCL-EP is driving the EP all-to-all — does it match anything you've seen? Feels like the UCCL proxy thread and a NCCL stream stepping on each other, but we don't have a clean repro outside of full Megatron training.
3. Is Megatron-core 0.17's `MoEFlexTokenDispatcher` a supported integration surface today, or is the expected path an older Megatron release / a different dispatcher? The two patches above are the minimum we needed to get past step 1; I'd rather delete them if upstream already has a supported path.
4. Are there official end-to-end Megatron training numbers (not microbench) for UCCL-EP on EFAv3? Microbench matching paper numbers but training being ~5× slower than NCCL-native is a large gap, and I'd like to know whether 7–8 % MFU floor is expected overhead here or a bug.

**Similar symptoms**:

- #878 — different model (Qwen3-235B), dtype (BF16 normal mode), parallelism (EP=16 PP=8 VPP=2), and runtime (verl + Ray), but same fabric (p5en EFAv3) and same DeepEP-atop-UCCL stack; similar `DeepEP timeout` flavor of failure.

**Comment by YangZhou1997** [comment]
Hi @AutoJunjie , we only tested UCCL-EP integration on the AMD version of Megatron-lm/Primus on AMD GPU + Broadcom NICs: https://github.com/uccl-project/uccl/tree/main/ep/bench/megatron done by @zhenhuang12 . Unfortunately, we are lacking AWS machines to do Megatron-LM integration or benchmarking for AWS EFA NICs. We use high-throughput mode for training, while low-latency is usually for inference. As far as I know, AWS EFA networks have poor low-latency performance, so we suggest using high-throughput instead. Btw, `test_internode.py` measures the high-throughput performance. 

@MaoZiming have you seen such timeout errors?

**Comment by zhenhuang12** [comment]
1. `EP_HOST_ASSERT(previous_event.has_value() and async)` will fixed in this pr https://github.com/uccl-project/uccl/pull/892
2. I think the timeout for deepep is too short; this error is a known issue https://github.com/NVIDIA-NeMo/Megatron-Bridge/blob/main/docs/releases/known-issues.md.

cc @YangZhou1997

**Comment by zhenhuang12** [comment]
BTW, I've also been looking into async comm stream lately, and I've tried forcibly changing `comm_stream` to `current_stream`. This can improve performance and also help you confirm if the issue is about async stream. you can try my branch `ep-fix-amd-force-current-stream`, just set env `export UCCL_EP_FORCE_CURRENT_STREAM=1` . this branch also fixed the error of  `EP_HOST_ASSERT(previous_event.has_value() and async)` @AutoJunjie 

cc @YangZhou1997

**Comment by AutoJunjie** [comment]
I can provide AWS machines, if you are interested, please give me your email or find me at zbcd016@gmail.com @zhenhuang12

**Comment by YangZhou1997** [comment]
Thank you, @AutoJunjie. I am cc'ing @MaoZiming if you are interested and have time.

**Comment by AutoJunjie** [comment]
@MaoZiming Bro let me know if you have time to dig into this

**Comment by MaoZiming** [comment]
@AutoJunjie Thanks for the issue. I plan to take a look at it over weekend. Unfortunately I was tied up with other stuff for the past few days. Definitely interested in trying out your workload/bug. My email is ziming.mao@berkeley.edu if emailing is easier for you.

**Comment by Schilings** [comment]
+1, hitting the exact same failure mode on a similar setup. Adding two independent data points that may help narrow it down.

### Environment
- AWS EFA cluster, 8× GPU per node (H-series), multi-EFA NICs per node (non-p5en; I'll note the NIC-count variability below)
- UCCL-EP built from source, with two local patches to get past EFA-specific blockers:
  1. `ep/include/common.hpp`: force-enable `USE_DMABUF` under `#ifdef EFA` — same root cause as @AutoJunjie's `ibv_reg_mr_iova2 → ENOTSUP` (stock wheel is unusable on our fabric too).
  2. `ep/src/rdma.cpp`: added a round-robin fallback for `num_efas ∉ {8, 16}`, so NIC selection still works on p6-b200 (8 EFAs) / p6-b300 (14 EFAs) / other future topologies. The original assertion `num_efas == 8 || num_efas == 16` crashes immediately on these SKUs.
- Megatron-style MoE training, custom `torch.autograd.Function` wrapper around `buffer.dispatch` / `buffer.combine` (basically DeepEP's fused dispatch/combine, with `previous_event = buffer.capture()` threaded through).

### Observations (matches #893 + two extras)
| Case | Result |
|---|---|
| `test_internode.py` microbench | ✅ passes, BW matches published numbers |
| Actual training | ❌ **crashes unpredictably mid-run**, no prior warning, no deterministic step |
| **Intranode**, `async_finish=True`, `allocate_on_comm_stream=True` (dispatch & combine, fwd & bwd) | ✅ runs |
| **Internode, ASYNC w/ overlap**: `async_finish=True`, `allocate_on_comm_stream=True` | ❌ **deterministic crash** — cannot get compute-comm overlap on internode |

**Comment by MaoZiming** [comment]
@Schilings Thanks! We can start a new issue; we have resolved the issue offline with @AutoJunjie (the training now runs stably with performance gains), and we are putting together findings to run MegatronLM training in both this PR (https://github.com/uccl-project/uccl/pull/903) and a more detailed guide (https://github.com/uccl-project/uccl/pull/914).

Re: ii, I agree! the NIC detection logic needs to be fixed with latest p6-b200 and p6-b300.

**Comment by YangZhou1997** [comment]
@Schilings Would be great if you could open a PR about your fix! Btw, why are there 14 NICs on p6-b300?

**Comment by YangZhou1997** [comment]
@Schilings https://github.com/uccl-project/uccl/pull/950 should support p6-b300
