### ISSUE TITLE
UCCL-EP: Silent Deadlock with 256 Experts + FP8 + EP=16 (TP=1/DP=16)

### ISSUE THREAD

**Issue by pbelevich** [uccl-project/uccl#923]
## Summary

UCCL-EP `deepep_low_latency` backend hangs indefinitely during initialization when used with DeepSeek-V3-0324 (256 experts, FP8) at TP=1/DP=16/EP=16 topology. No error is produced — the process simply never returns from EP init.

## Severity

High — silent hang with no diagnostic output makes debugging impossible.

## Environment

| Component | Version |
|-----------|---------|
| vLLM | 0.20.0 |
| UCCL-EP | commit `8ac850bdff72e44979d461032fa8fde98f07ca7a` |
| PyTorch | 2.11.0+cu130 |
| CUDA | 13.0.3 |
| NVIDIA Driver | 580.105.08 |
| NCCL | 2.30.4-1 |
| EFA Installer | 1.48.0 |
| GDRCopy | 2.5.2 |

## Hardware

- Instance: 2× AWS p5en.48xlarge
- GPU: 8× NVIDIA H200 (141 GiB) per node (16 total)
- Network: 16× EFA devices per node

## Steps to Reproduce

1. Deploy DeepSeek-V3-0324 across 2 nodes with TP=1/DP=16 topology:
```bash
# Head node
vllm serve deepseek-ai/DeepSeek-V3-0324 \
  --tensor-parallel-size 1 \
  --data-parallel-size 16 \
  --enable-expert-parallel \
  --all2all-backend deepep_low_latency \
  --gpu-memory-utilization 0.85 \
  --trust-remote-code \
  --data-parallel-address <head_ip> \
  --api-server-count 16

# Worker node
vllm serve deepseek-ai/DeepSeek-V3-0324 \
  --tensor-parallel-size 1 \
  --data-parallel-size 16 \
  --enable-expert-parallel \
  --all2all-backend deepep_low_latency \
  --gpu-memory-utilization 0.85 \
  --trust-remote-code \
  --headless \
  --data-parallel-start-rank 8 \
  --data-parallel-address <head_ip>
```

2. Model loads successfully on all 16 ranks.
3. Process hangs indefinitely during UCCL-EP initialization (after NCCL init completes).

## Observed Behavior

- NCCL world init completes successfully (world_size=16)
- Model weights load on all ranks
- Process hangs with no output, no error, no timeout
- Must be killed manually (SIGKILL)

## Contrast: Working Configuration

The **same model** with TP=8/DP=2 (EP=2 peers) works perfectly with deepep_ll:
```bash
vllm serve deepseek-ai/DeepSeek-V3-0324 \
  --tensor-parallel-size 8 \
  --data-parallel-size 2 \
  --enable-expert-parallel \
  --all2all-backend deepep_low_latency \
  ...
```
This achieves 24.3ms P50 TPOT — best DSv3 latency measured.

## Root Cause Hypothesis

The issue appears related to the number of EP peers. With TP=8/DP=2, there are only 2 EP endpoints. With TP=1/DP=16, there are 16 EP endpoints. The RDMA connection setup between all pairs of 16 endpoints likely exceeds some connection or memory limit, causing a deadlock in the init handshake.

## Expected Behavior

Either:
1. Successfully initialize EP with 16 peers
2. Timeout and produce a clear error message indicating the peer count limit

## Suggestion

Add a configurable timeout to UCCL-EP initialization with diagnostic output showing:
- How many peers were expected
- How many QPs were successfully created
- Where the hang occurred (which peer pair)

cc: @nkumaraws @xuzhiying9510

**Comment by MaoZiming** [comment]
Hi Thanks for the issue! @pbelevich Can you try it on the latest main branch? It might be fixed on this branch: https://github.com/uccl-project/uccl/pull/903

**Comment by MaoZiming** [comment]
I just run on latest main and it worked on 2 **p5en**:

## 1. Hardware

| Role | Public IP | Private IP | Interface |
|---|---|---|---|
| Node 1 (head) | xxx | yyy | `enp71s0` |
| Node 2 (worker) | xxx | yyy | `enp71s0` |

Both nodes: AWS p5en.48xlarge, 8× NVIDIA H200 (141 GB HBM each), 16× 200 Gb/s EFA NICs (`rdmap{85..163}s0`), driver 580.95.05 (CUDA 13.0), nvcc 12.9 at `/usr/local/cuda-12.9`.

---

## 2. Software stack (installed into base conda env on both nodes)

| Component | Version | Install method |
|---|---|---|
| Miniconda3 | latest | `bash /home/ubuntu/efs/Miniconda3-latest-Linux-x86_64.sh -b -p /home/ubuntu/miniconda3` |
| Python | 3.13.11 | bundled with miniconda |
| torch / torchvision / torchaudio | 2.11.0+cu129 | `ep/install_deps.sh` (auto-detected cu129 from nvcc) |
| uccl.ep | HEAD `605e8f2b` | `cd ep && PER_EXPERT_BATCHING=1 python setup.py install` |
| deep_ep_wrapper (DeepEP drop-in) | repo | `cd ep/deep_ep_wrapper && python setup.py install` |
| DeepGEMM | 2.5.0+891d57b | `git clone --recursive https://github.com/deepseek-ai/DeepGEMM && bash install.sh` |
| vLLM | 0.20.0 | `pip install vllm==0.20.0` |
| py-spy | 0.4.2 | `pip install py-spy` (debug only) |

OS packages required (`sudo apt install -y …`):
- `libnuma-dev` — for `numaif.h` (uccl.ep build fails without it)
- `ninja-build` — speeds uccl.ep build
- `nvidia-cuda-toolkit` — provides `cuobjdump` at `/usr/bin/cuobjdump`
- Then: `sudo ln -sf /usr/bin/cuobjdump /usr/local/cuda/bin/cuobjdump` (DeepGEMM looks here)

Model used: `/home/ubuntu/efs/zm/models/DeepSeek-V3-0324` (642 GB FP8 on EFS).

Notes / divergences from the original issue's stack:
- Issue reports torch 2.11.0+cu130; this env uses cu129 (because nvcc is 12.9). Torch major/minor matches.
- Issue reports vLLM 0.20.0 — exact match.
- Issue does not specify uccl.ep commit; current HEAD includes the #903 fix.

---

## 3. Network env vars (used by both tests)
```bash
export NCCL_SOCKET_IFNAME=enp71s0
export UCCL_SOCKET_IFNAME=enp71s0
export GLOO_SOCKET_IFNAME=enp71s0
export TP_SOCKET_IFNAME=enp71s0
export NCCL_IB_GID_INDEX=0
export UCCL_IB_GID_INDEX=0
export NCCL_NET_PLUGIN=/opt/amazon/ofi-nccl/lib/libnccl-net.so
export NCCL_DEBUG=INFO
```
## 4. Test -- Full vLLM `deepep_low_latency` (the actual issue config)

### Configuration: TP=1, DP=16, EP=16 (8 ranks × 2 nodes)

### Script (`/tmp/run_vllm_node1.sh`)
```bash
#!/bin/bash
set -e
source /home/ubuntu/miniconda3/etc/profile.d/conda.sh && conda activate base

# Critical: torch libs must be on LD_LIBRARY_PATH for uccl.ep .so to load libc10.so
export LD_LIBRARY_PATH=/home/ubuntu/miniconda3/lib/python3.13/site-packages/torch/lib:$LD_LIBRARY_PATH
export VLLM_USE_DEEP_GEMM=1
export GLOO_SOCKET_IFNAME=enp71s0
export NCCL_SOCKET_IFNAME=enp71s0
export TP_SOCKET_IFNAME=enp71s0
export UCCL_SOCKET_IFNAME=enp71s0
export NCCL_IB_GID_INDEX=0
export UCCL_IB_GID_INDEX=0
export NCCL_NET_PLUGIN=/opt/amazon/ofi-nccl/lib/libnccl-net.so
export NCCL_P2P_NET_CHUNKSIZE=524288
export NCCL_BUFFSIZE=8388608
export NCCL_DEBUG=INFO
export VLLM_ENGINE_READY_TIMEOUT_S=3600
mkdir -p /opt/dlami/nvme/dg_cache 2>/dev/null || true
export DG_JIT_CACHE_DIR="/opt/dlami/nvme/dg_cache"

cd /tmp
exec vllm serve /home/ubuntu/efs/zm/models/DeepSeek-V3-0324 \
  --enable-expert-parallel \
  --all2all-backend deepep_low_latency \
  --tensor-parallel-size 1 \
  --data-parallel-size 16 \
  --data-parallel-size-local 8 \
  --data-parallel-address 172.31.8.68 \
  --data-parallel-rpc-port 13345 \
  --gpu-memory-utilization 0.85 \
  --trust-remote-code \
  --api-server-count=1
```

### Script (`/tmp/run_vllm_node2.sh`)
Same env block, but the launch is the headless worker:
```bash
exec vllm serve /home/ubuntu/efs/zm/models/DeepSeek-V3-0324 \
  --enable-expert-parallel \
  --all2all-backend deepep_low_latency \
  --tensor-parallel-size 1 \
  --data-parallel-size 16 \
  --data-parallel-size-local 8 \
  --data-parallel-start-rank 8 \
  --data-parallel-address 172.31.8.68 \
  --data-parallel-rpc-port 13345 \
  --gpu-memory-utilization 0.85 \
  --trust-remote-code \
  --headless
```

### Timeline observed
| Time (mm:ss from launch) | Event |
|---|---|
| 0:00 | Launch |
| ~0:30 | Engine cores spawned (`EngineCore_DP0..15`), `Initializing a V1 LLM engine (v0.20.0)` |
| ~1:00 | NCCL/EFA init, `NCCL version 2.28.9+cuda12.9`, 16 EFA NICs detected |
| ~1:10 | `Using DeepEPLLAll2AllManager all2all manager` ← uccl-ep wrapper engaged |
| ~1:30 | Workers start `Loading safetensors checkpoint shards: 0/163` |
| ~1:30 → ~12:00 | Weight load (EFS NFS-bound; first shard ~250 s cold, later <2 s) |
| ~12:00 | `Using DeepEPLLPrepareAndFinalize` ← issue's reported hang point |
| ~13:00 | `Compiling a graph for compile range (1, 256) takes 11.03 s` |
| ~14:00 | `DeepGEMM warmup: 0/308` → `308/308` |
| ~14:30 → ~22:00 | `Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 0/35` → `35/35` per rank |
| ~17:00 → ~22:00 | `shm_broadcast: No available block in 60s` warnings — **expected** during graph capture (vLLM's own logging says so); py-spy confirmed workers were on `_capture_cudagraphs`, not on any RDMA wait |
| ~22:30 | All ranks done capture; KV cache allocated (GPU mem 60→125→131 GB / GPU) |
| **23:00** | **`Application startup complete.`** |
| 23:30 | `POST /v1/completions` returned a valid 10-token response |

### Verification request
```bash
curl -sS -X POST http://localhost:8000/v1/completions \
  -H 'Content-Type: application/json' \
  -d '{"model":"/home/ubuntu/efs/zm/models/DeepSeek-V3-0324","prompt":"Hello","max_tokens":10}'
```
Returned a valid completion → end-to-end MoE forward through the deepep_low_latency backend works.
